version: "3"
services:
  
  zookeeper:
    image: debezium/zookeeper:1.8
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:1.8
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  
  mysql:
    image: debezium/example-mysql:1.8
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw 
  
  connect:
    image: debezium/connect:1.8
    build:
      context: debezium
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafka
      - mysql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses

  django:
    build:
      context: .
      dockerfile: django.Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=inventory
      - DB_USER=mysqluser
      - DB_PASSWORD=mysqlpw
      - DB_HOST=mysql
    volumes:
      - ./sor:/sor
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - mysql

  faust:
    container_name: faust
    build: 
      context: .
      dockerfile: faust.Dockerfile  
    command: faust -A soa_app worker -l info
    depends_on:
      - kafka