version: "2.2"

services:
  aiobankingui:
    container_name: aiobankingui
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
      - "/app/node_modules"
    ports:
      - 3001:3000
      - 35729:35729
    environment:
      - CHOKIDAR_USEPOLLING=true
